# Generated by Django 5.2.1 on 2025-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.TextField(choices=[('happyfox_helpdesk', 'HappyFox Helpdesk'), ('happyfox_service_desk', 'HappyFox Service Desk')])),
                ('account_reference', models.TextField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
