# Generated by Django 5.2.1 on 2025-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='estimated_duration',
        ),
        migrations.AddField(
            model_name='lesson',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True),
        ),
    ]
