# Generated by Django 5.2.1 on 2025-05-15 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video File'), ('presentation', 'Presentation (e.g., PPT, Keynote)'), ('document', 'Text Document (e.g., DOCX, TXT)'), ('spreadsheet', 'Spreadsheet (e.g., XLSX, CSV)'), ('image', 'Image File'), ('audio', 'Audio File'), ('archive', 'Archive File (e.g., ZIP, RAR)'), ('web_link', 'Web Link'), ('other', 'Other File Type')], max_length=255)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
            },
        ),
        migrations.CreateModel(
            name='DataSourceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=255)),
                ('title', models.CharField()),
                ('raw_content', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_sources.datasource')),
            ],
            options={
                'verbose_name': 'Data Source Content',
                'verbose_name_plural': 'Data Source Contents',
                'unique_together': {('data_source', 'reference_id')},
            },
        ),
    ]
