# Generated by Django 5.2.1 on 2025-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcecontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content_files/%Y/%m/%d/'),
        ),
    ]
